name: silaan_logistic
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.5.2
  flutter_svg: ^1.0.3
  fl_chart: ^0.55.0
  firebase_core: ^1.19.1
  firebase_auth: ^3.3.20
  webview_flutter: ^3.0.4
  shared_preferences: ^2.0.15
  cloud_firestore: ^3.2.0
  intl: ^0.17.0
  google_maps_flutter: ^2.1.8
  image_cropper: ^2.0.3
  image_picker: ^0.8.5+3
  firebase_storage: ^10.3.1
  cached_network_image: ^3.2.1


dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true


  assets:
    - assets/onboarding/
    - assets/icons/
    - assets/images/
    
  fonts: 
    - family: IMFellDoublePica
      fonts: 
        - asset: assets/font/IM_Fell/IMFellDoublePica-Regular.ttf
          weight: 400
    - family: Actor
      fonts: 
        - asset: assets/font/Actor/Actor-Regular.ttf
          weight: 400

